/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class jnidemojava_Resample */

#ifndef _Included_jnidemojava_Resample
#define _Included_jnidemojava_Resample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jnidemojava_Resample
 * Method:    nativePrint
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jnidemojava_Resample_nativeEcho
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif